# PYCZMQ
#
# After modifying this file check it using: http://lint.travis-ci.org/
#

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# Perform regression test build against latest dependencies

before_install: 
  # Install Python dependencies
  - pip install --use-mirrors -r requirements.txt

  # Install C library dependencies

  # sodium
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure
  - make check
  - sudo make install
  - sudo ldconfig
  - cd ..

  # zmq
  - git clone git://github.com/zeromq/libzmq.git
  - cd libzmq
  - ./autogen.sh
  - ./configure && make check
  - sudo make install
  - sudo ldconfig
  - cd ..

  # czmq
  - git clone git://github.com/zeromq/czmq.git
  - cd czmq
  - ./autogen.sh
  - ./configure && make check
  - sudo make install
  - sudo ldconfig
  - cd ..


install:
  - python setup.py install

# Test and install PYCZMQ
script:
  - nosetests

